### ISSUE TITLE
Track combatant concentration

### ISSUE THREAD

**Issue by tylerdave** [mpirnat/dndme#10]
During an encounter you should be able to track when a combatant is concentrating for the duration of the spell / effect.

**Comment by mpirnat** [comment]
Should be able to cancel it too when concentration is interrupted.

**Comment by mpirnat** [comment]
Assuming we can treat concentration as just another condition, I added the support for most of this in 546d5efe51c4c0c113aff37ffba6a4b30ca32bcd, 6b2b0ba077110d279d82579abc32f890d85b8d41, and 4436ef2200cca7b01e811babbc9393367f5d3471.

Right now it can be manually canceled by just unsetting it. It might be nice to prompt to check for interruption when a target receives damage, but that's probably a separate issue.
