### ISSUE TITLE
Add summoned creatures to initiative order

### ISSUE THREAD

**Issue by JohnRoach** [mpirnat/dndme#16]
Some summoned creatures have their own initiative. We need to add summoned creatures to the initiative order.

**Comment by mpirnat** [comment]
I don't think this has a huge priority; having summoned creatures act in the same turn as their summoner is a pretty common house rule, and how I intend to proceed for now to keep things simple. The notion of keeping things simple should be the guiding principle in all things with this project.

**Comment by tylerdave** [comment]
Can't this be handled well enough by supporting adding an arbitrary combatant anyway?

**Comment by mpirnat** [comment]
Sure, but I’m advocating for not even doing it at all, or at least for right now.

**Comment by JohnRoach** [comment]
@mpirnat ok.
@tylerdave regarding adding arbitrary combatants, unlike arbitrary combatants I was thinking of putting a timer on summoned creatures where when the timer runs out the creatures will act according to the rules they are bound by.

**Comment by mpirnat** [comment]
Initial solve in e2da502637062c37a900b370497d240625edb037.

I'll need to add a command to remove monsters (eg summoned monsters are dismissed without being defeated), but that shouldn't be too hard.
