### ISSUE TITLE
Organize encounters for easier selection

### ISSUE THREAD

**Issue by mpirnat** [mpirnat/dndme#21]
Eventually, there will be a lot of encounters to choose from. We need to think about how they might best be organized and presented for loading. Is there just a giant list that a DM would page through before making a selection? Is there some kind of nested/tree structure that the DM can navigate to pick an encounter?

**Comment by JohnRoach** [comment]
I am sorry, need more information regarding the how encounters work. Are these all random? or are some random?

**Comment by mpirnat** [comment]
A typical adventure consists of encounters of both the planned and random variety.

Planned encounters take place at particular locations defined and, in printed materials, are defined in the text describing the location. When I'm running Lost Mine of Phandelver with you, the text I'm referring to in order to know what's going on describes the setting, with some text to read to the players, and notes for the DM about the location (traps, puzzles, treasures, etc.) and whatever NPCs or foes are present. Since these encounters are planned as part of the story, they have a fixed challenge level and thus a fixed number of combatants. To prepare for our gaming sessions, I make up an encounter sheet with a copy of the stat blocks for each type of combatant and any notes of interest. This way I don't have to go fishing around in the back of the adventure module or in the monster manual for a creature's stats when combat begins. An example of this type of encounter is included in this repository--the goblin ambush from the beginning of Lost Mine of Phandelver.

Adventures may also contain random encounters to add flavor or extra challenge along the way. They are not guaranteed to occur. They may be rolled for or picked deliberately by a DM to enhance the game. In printed materials, they are usually presented as a table of die rolls, the creature, and the number of those creatures--and this number may be fixed or based on a die roll. The table may contain both day and night variants, as for overland travel. Here's an example from Chapter 3 of Lost Mine of Phandelver:

<img width="339" alt="random encounters" src="https://user-images.githubusercontent.com/396822/33466494-67b7e164-d61c-11e7-895f-27db0387238b.png">

To prepare for random encounters, I make up encounter sheets for each possible encounter, again copying out the stat blocks for the appropriate creatures, and leave myself a note for how to figure out the number of them. I might roll for them (as I did in overland travel as y'all did the side quests in Chapter 3), or I might pick them deliberately to spice things up (as I've done in Wave Echo Cave a couple of times to keep you on your toes).

So, depending on the size of the adventure, there may be only a few planned encounters, or there might be many. Printed adventures typically group these into chapters (and chapters are thus grouped into overall adventures). A DM may have multiple adventures going for different groups.

This issue is about the user experience of picking an encounter--whether planned or random--from a potentially large number of encounters that make up an adventure. I like rolling real dice (or just picking something appropriate) so I don't think the tool has to determine which random encounter to serve up; it just has to make it easy to find and access what I want.

**Comment by mpirnat** [comment]
Sort of taking the easy way out on this in dc97df3 by allowing the encounters directory to be specified at startup... So instead of having to navigate between campaigns and between chapters to get the right list of encounters to show, the user would just tell us explicitly when starting up the shell; for example:

`python shell.py --encounters=~/dnd/campaigns/lost_mine/chapter3`

This cheap approach assumes that one doesn't have to go fishing in other chapters in mid-session, which is probably acceptable for now.

Alternatively maybe load encounter becomes a multi-argument subcommand within the shell and does prompt toolkit based autocompletion instead of the more old-school "print and prompt for a pick" approach currently in place.

**Comment by mpirnat** [comment]
I'm wondering if, now that we've added filtering in https://github.com/mpirnat/dndme/commit/524b67a26be6b0ccdd75a9f8db0ca117059433be, we even need to do anything more on this... I'll play test it a little with my group and see how I feel.
