### ISSUE TITLE
Save and reload state

### ISSUE THREAD

**Issue by johnroach** [mpirnat/dndme#28]
We need a way to save the current state and later on reload it.

**Comment by JohnRoach** [comment]
I had been away too much from this project. @mpirnat added awesome improvements and features. Need to revisit this. However for now removing myself as assignee so I won't stifle anyone's enthusiasm to complete this ticket.

**Comment by mpirnat** [comment]
I kind of did a very basic version of this in #63 in which we can now save an updated party.toml file. But there's quite a ways to go to do this full justice.

**Comment by mpirnat** [comment]
I'm going to close this since I've got _basically_ what I need for right now.
