### ISSUE TITLE
Hey how about some tests?

### ISSUE THREAD

**Issue by mpirnat** [mpirnat/dndme#40]
I have so far been lazy and not written any tests for anything because all the code has been very experimental and exploratory. At some point it would be good to have tests. This issue can be closed by setting up a test suite with at least a couple of tests and documenting procedures for running them.

**Comment by befreeman** [comment]
I am working on configuring pytest & tox. This would also require doing a bit of package configuration.
I'll try to keep things as minimal as practical and in-line with the current configuration.

I'll also provide testing documentation for the README.md

**Comment by mpirnat** [comment]
Merged and successfully ran tests with pytest. Thanks, @befreeman!
